apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    service: shipping
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        service: shipping
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipping.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: shipping
        image: {{ .Values.image.repo }}/rs-shipping:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        # it's Java it needs lots of memory
        resources:
          {{- toYaml .Values.shipping.resources | nindent 10 }}
        {{- with .Values.shipping.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.shipping.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- if or .Values.shipping.affinity .Values.shipping.antiAffinity }}
      affinity:
        {{- with .Values.shipping.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.shipping.antiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.shipping.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipping.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
