apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web
  {{ if .Values.nodeport }}
  type: NodePort
  {{ else }}
  type: {{ .Values.web.serviceType }}
  {{ end }}
---
{{if .Values.ocCreateRoute}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: web
{{end}}
